name: Generate ADHD 1400-Char Key / [[1]]
on:
  schedule:
    - cron: '*/25 * * * *'
  workflow_dispatch:

jobs:
  update-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Chaos Key
        run: |
          echo "25_min_pass_GO_PASTE_THIS_RIGHT_NOW_$(openssl rand -hex 700 | head -c 1390)" > active_key.txt
      - name: Commit and Push
        run: |
          git config --global user.name "Cron-Bot"
          git config --global user.email "bot@cron.com"
          git add active_key_1.txt
          git commit -m "Rotate hash [25m interval]" || exit 0
          git push
